### ISSUE TITLE
[Discuss] DevSecOps & Design de Nuvem

### ISSUE THREAD

**Issue by midhatdrops** [lbarcat/DevOps4noobs#2]
# 1. DevSecOps

Apesar de DevOps ser um movimento/cultura, muito se ganhou na abordagem agora de DevSecOps, acho que seria legal dar uma ampliada no assunto com algumas coisas de Sec(SAST,SAC) ou de QA no processo de CI/CD (sonar, veracode/fortify, cucumber, entre outras ferramentas).

# 2. Design de Nuvem

Acho que a parte de design de nuvem não cabe exatamente aqui ou deveria ser um tópico mais voltado para arquitetura. Não sei se você concorda com essa visão ou quando disse design de nuvem quis dizer voltado para arquitetura para devSecOps.

**Comment by lbarcat** [comment]
# 1. DevSecOps

A respeito do DevSecOps é legal incluir também, abordando os principais pontos a respeito do assunto, nesse caso qual o tópico que mais se encaixa no RoadMap? Vou pesquisar e ler alguns materiais a respeito.
Quanto ao QA também acho relevante, estou fazendo um curso que envolve sonar por exemplo e posso comentar a respeito. 

# 2. Design de Nuvem

Eu estava pensando em colocar os seguintes tópicos: Disponibilidade, Gestão de Dados, Desenho e Implementação, Gestão e Monitorização. Não sei se encaixa na questão do DevSecOps.

As idéias são excelentes, vamos fazer!

**Comment by midhatdrops** [comment]
1. Creio que a parte de análises de vulnerabilidades (algumas ferramentas) seja a que mais se encaixe aqui.
2. Acho que encaixa sim, só não tomaria cuidado para não entrar demais na parte de arquitetura ( a nível deep-dive)

**Comment by lbarcat** [comment]
Inseri algumas coisas em design de nuvem, veja se ficou legal. 

Eu inseri mais dois tópicos no final: DevSecOps e Ferramentas Atlassian para DevOps. 

Se puder, encaixe a parte de análises de vulnerabilidades no tópico 16 explicando um pouco do conceito também, acho que fica legal. Essa parte é totalmente nova pra mim. 

Vou finalizar depois com o tópico 17.

Já coloquei os caminhos no RoadMap.

**Comment by lbarcat** [comment]
Adicionei o DevSecOps, mas se achar necessário pode abrir PR. Valeu!!
